### ISSUE TITLE
Possibility of adding new directory with template files

### ISSUE THREAD

**Issue by iammarkoradak** [AlexeySokolov/atom-smart-template#2]
First off - great tool! It should get more attention, imo.

I think it would make it even better if there was an option of adding a (dynamic name) directory with template files. A name parameter would be passed from current params array. In order for it to work correctly, there would be an option to create directory or not (within every template). Something like on a screenshot below. 

I have tested (a pretty straight forward) implementation - so if you're up for it, I can submit a PR with the changes. :smiley:

![screenshot 2016-04-17 00 46 16](https://cloud.githubusercontent.com/assets/9327301/14584058/d0a4e254-0435-11e6-9569-9a597c9a67ec.png)

**Comment by iammarkoradak** [comment]
In case "Name" parameter is not provided, it would name a directory after templates name.

**Comment by AlexeySokolov** [comment]
Hi, Marko.
Thanks for the interest. Create a pull request.
I will consider your improvements.

**Comment by iammarkoradak** [comment]
Just did :)
